version: '3.8'
services:
  web:
    build: ./FE
    ports:
      - 3000:3000
    image: tretton37_web:1
  api:
    build: ./BE
    ports:
      - 3001:3001
    image: tretton37_api:1
    environment:
      DATABASE_URL: postgres://postgres:changethispw@db:5432/t37db
    command: ['sh', './docker-entrypoint.sh']
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: changethispw
      POSTGRES_DB: t37db
    restart: unless-stopped
