version: '3.8'
services:
  api:
    build: ./BE
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: postgres://postgres:changethispw@db:5432/t37db
    volumes:
      - ./BE:/app
    command: ['sh', './docker-entrypoint.sh']
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: changethispw
      POSTGRES_DB: t37db
    restart: unless-stopped
